wagtail/outreachy

2023/README.md

@thibaudcolas This is my first pull request with Wagtail 🥳

Add Chiemezuo to 2023/readme

---

2023/Arafat/README.md

Added a README markdown file introducing myself as a new contributor

doc: new contributor information

---

2023/README.md

I have added my name to the list whilst keeping in mind that it has to be in order.

doc: add my name

---

2023/Ahmed Olaitan/README.md
2023/Ahmed-Olaitan/README.md
2023/README.md

Hi @thibaudcolas I have added my name to the list as requested

Add my name

---

2023/README.md
2023/cynthiaudoh/README.md
2023/cynthiaudoh/README.md.txt

My name has been added to the Outreachy 2023 participant.

Name Added

---

2023/Chidera_Stella_Onumajuru/README.md
2023/README.md

- Added my name to 2023 README.md.
-  Created a personal folder.
-  Added personal detail table.
-  Added contributor tasks checklists.
@

Chidera Personal details

---

2023/Olumide/README.md

This pull request contains the checklists of everything required for me to do as a contributor

doc: added introductory message, socials, and tasks

---

2023/Praise_Agbabiaka/README.md
2023/README.md

I added my name to the list of participants. I also recreated a folder where I included an introduction, contact details and the checklists of tasks specific to my project of interest, with completed tasks checked off.

Add Praise_Agbabiaka

---

2023/Kudakwashe Chris Chipangura/README.md

Added folder with my name and readme with my Wagtail intro and personal info

Added A folder with my name (Kudakwashe Chris Chipangura)

---

2023/Ihedioha-Chinedu/README.md
2023/README.md

This is a pull request that contains the checklists required for a contributor with Wagtail 
1. Added my name to the list of participants in [2023/README.md](https://github.com/wagtail/outreachy/blob/main/2023/README.md).
2. Created a new folder inside 2023/ with my name as the folder name. 
3. Inside that folder, I added a README.md file with my personal introductory message.
4. Added the task section
5. Added contributor's checklist
6. Added Research section

doc: updated my personal folder and the README.md with task checklist

---

2023/Geoffrey-Logovi/README.md
2023/README.md

doc: update the applicants 2023/README and add geoffrey intro

---

2023/Kudakwashe Chris Chipangura/README.md

Added task section to my profile in  Kudakwashe Chris Chipangura/readme.md

Added tasks section

---

2023/README.md

Adding my name to the readme with list of all participants names

Adding my name to the readme

---

2023/fortune_obadiah
2023/my first pull

I added a ReadMe.md file Introducing myself and my social links.

Update and rename my first pull to fortune_obadiah

---

2023/Naomi Ibe/README.md

As part of my Outreachy contribution phase for the WAGTAIL project, I'm submitting this file which contains some key details about myself

My Introductory Readme.md file

---

2023/Cole Kofoworola/README.md
2023/README.md

My first PR , I added Cole Kofoworola

---

2023/Kehinde Bobade/README.md
2023/README.md

- Updated readme file with my name
- Included my name folder with readme file containing introduction.

updated readme file and included name folder for Kehinde Bobade

---

2023/README.md

Hi, I have been assigned an issue on Wagtail issues page, kindly add my name to the Outreachy contributer's list.
Thank you!

Added Nishant in Outreachy Contributor's list.

---

2023/Meli-Imelda/README.md

feat: added meli-imelda intro

---

2023/Meli-Imelda/README.md

feat: added meli-imelda profiles

---

2023/Oghenekevbe Egume/README.md
2023/README.md

I opened my folder and created the README.md
Pasted my intro
I also added my name to the readme list and rearranged the list in ascending order (Alphabetically).

(Oghenekevbe) made my folder & organized the readme names

---

2023/Fortune_Obadiah/README.md

- I've included the contributor task assigned to me, along with the relevant research links.
- Additionally, I've uploaded the first two blog posts I created as part of the task.

[Fortune Obadiah] Update Readme  With Assigned Task

---

2023/Jude Okoye/Readme.md
2023/README.md

I did the following:
- Added my full name to /2023/README
- Created a folder in /2023 using the format '[full name]' 
- Created a file /Readme.md and updated the contents with the current tasks I have done.

My first contribution to Wagtail: Added 'Jude Okoye' to /2023/README

---

2023/Nwajei Edgar/README.md

Added
Proper links in a table
Getting started with Outreachy tasks
Open source contributions tasks
Research section
Recent learning blog post
Accessibility blog post
technical writing blog post

made necessary changes

---

2023/README.md

Added my name Eniola Oyebadejo to the list of participants of the Wagtail/Accessibility Features Documentation Project.

Update README.md....Add Name To List

---

2023/README.md
2023/Tunde Babatunde/README.md

Research Links found very useful are placed in the README file under the asking task

Research links

---

2023/Ikechukwu Arinze/README.md

Looking forward to your review!

Added my introduction and updated checklist to my README file.

---

2023/Birungi Mercy/README.md

My first fork had some issues , plus i was only pushing the folder and missing out the read.md file . this commit includes my intro . Next I will be adding the checklists and what I have completed and worked on . I have been having issues pushing but re cloning my fork helped

Add README.md with my intro

---

2023/Olumide/README.md

In this PR, I have made sure to add links to my blog post for the following:
1. [x] My **recent learning**
2. [x] My understanding of **accessibility**
3. [x] And my expertise in **technical writing**
The next step is gaining editor access to the Wagtail website. While waiting for that, I'll continue learning about Wagtail.

add links to blog posts

---

2023/Nouman Wali/READEME.md

I made the following changes to the Readme file
- Provide a professional look to Readme file
- Readme File heading
- Removed unnecessary content
- Icons to the headings
- Table of contents section
- Navigation to sections
- Added acknowledgement section
- Added authors section
-

Update Reademe File with Professional Template

---

2023/Igbo Ujunwa/README.md
2023/README.md

I did everything required and marked my checklist. I also added my personal file including the blogs and also I changed my Social media profile link. I did all the necessary requirements as an Applicant

Updated README.md and personal file with Blogs

---

2023/Meli-Imelda/README.md
2023/README.md

feat: updated tasks

---

2023/Nsingwire Victor/README.md

I made some new changes to my personal file, please help review and integrate them

update on Nsingwire Victor personal file

---

Eniola Oyebadejo

Task 1 Medium Blog
https://medium.com/p/fe63fac0060e/edit
Task 2 Medium Blog
https://medium.com/p/e94e6df6c261/edit

Wagtail Task 1 & 2  Blog Post

---

2023/Temidayo Azeez/README.md

This is my personal file  for Outreachy as required in `contributors.md`

Temidayo Azeez Personal File
